### ISSUE TITLE
w24cli techread --ask-canvas-thumbnail uses dict instead of bytes object

### ISSUE THREAD

**Issue by oktaysabak** [W24-Service-GmbH/werk24-python#159]
Hey, recently I noticed `w24cli techread --ask-canvas-thumbnail` raises `TypeError: a bytes-like object is required, not 'dict'` error. 

It should be `m.payload_bytes` instead of `m.payload_dict`  in line:

https://github.com/W24-Service-GmbH/werk24-python/blob/5c094f09594828787c76f2dd5aedf1fa8b233587/werk24/cli/techread.py#L71

**Comment by werk24** [comment]
Hi Oktay,

thank you for pointing it out. I created a pull request that is ready for review. 
We'll include the fix into the next release.

Cheers
