### ISSUE TITLE
Question - Licence AGPLv3

### ISSUE THREAD

**Issue by mathben** [W24-Service-GmbH/werk24-python#298]
The actual licence seems to be Proprietary Open Source.
"The Licensed Work is (c) 2020 W24 Service GmbH"

I am a "free as freedom" (copyleft) developer.
Question 1 : Is the licence of this project compatible with AGPLv3?
https://www.gnu.org/licenses/license-list.en.html
Question 2 : Can the project werk24-python can be released with an hybrid licence, AGPLv3 or "(c) 2020 W24 Service GmbH" ?

**Comment by werk24** [comment]
Hi mathben,  cool work you are doing. 

the project is a pure client that allows the communication with the werk24 servers. It has no functionality besides that.
