### ISSUE TITLE
SSL Verification Issue caused by aiohttp

### ISSUE THREAD

**Issue by jmtts** [W24-Service-GmbH/werk24-python#316]
**Describe the bug**
Aiohttp 3.10.1 and 3.10.2 have trouble with the validation of SSL certificates (https://github.com/aio-libs/aiohttp/issues/3080).
That causes error error messages at seemingly arbitrary moments. Release 3.10.3 fixes it (https://github.com/aio-libs/aiohttp/releases/tag/v3.10.3)

**Comment by werk24** [comment]
closed by #317
