### ISSUE TITLE
SheetAnonymization needs a PDF Output format

### ISSUE THREAD

**Issue by werk24** [W24-Service-GmbH/werk24-python#332]
**Is your feature request related to a problem? Please describe.**
A customer requested PDF as output format for the SheetAnonymization. 

**Describe the solution you'd like**
The `W24AskSheetAnonymization` should get a parameter `output_format` that defaults to the current value `PNG`, but also allow PDF. The value should be of type `W24FileFormatThumbnail`, accepting that the name can be a bit confusing. The alternative, of having two very similar enums would however even be more confusing. 

**Describe alternatives you've considered**
As an alternative we could 
1. create a second enum, e.g, `W24FileFormatSheet`, but it's difficult to come up with a good name and would duplicate very similar values.

**Comment by jmtts** [comment]
This will also affect the existing thumbnails, because we now allow the user to request PNG and JPEG outputs!

**Comment by jmtts** [comment]
addressed in #333

**Comment by jmtts** [comment]
We need to be careful with the content-type. This might be hard-coded sofar

**Comment by jmtts** [comment]
In `W24AskThumbnail` we call the parameter `file_format`, rather than `output_format`. For consistency purposes we need to change the naming to `file_format` here as well.

**Comment by werk24** [comment]
closed by #333
